@startuml
'https://plantuml.com/component-diagram

database "MySql" {
  folder "This is my folder" {
    [Folder 3]
  }
  frame "Foo" {
    [Frame 4]
  }
}

package  Nutzer {
    [Auth]
    [Friends]
    [Registration]
    [AuthVerify]
    [NutzerManagement]

    database NutzerRead
    database NutzerWrite
    database FriendsRead
    database FriendsWrite
    database NutzerUnVerified
    database FriendInvites
    database Tokens
}

package Lobby {
    [StdLobby]

    database StdLobbyData
    database LobbyInvites

    LobbyInvites -- LobbyEventBus
}


NutzerWrite --> NutzerRead
NutzerUnVerified --> NutzerWrite
FriendsWrite --> FriendsRead

[Auth] --> NutzerRead
[Auth] --> Tokens
[AuthVerify] --> Tokens
[Registration] --> NutzerUnVerified
[Registration] --> NutzerWrite
[NutzerManagement] --> NutzerWrite
[Friends] --> FriendsWrite
[Friends] --> FriendInvites

[StdLobby] --> FriendsRead
[StdLobby] --> LobbyInvites
[StdLobby] --> NutzerRead

@enduml